In [19]:
import numpy as np

EJERCICIO #1: 

Construya el algoritmo de multiplicación de matrices y encuentre el resultado de las siguientes operaciones.

Algoritmo:

In [20]:
def multiplicacion(A,B):
      
    M,N = A.shape
    R,T = B.shape

    if R==1:
        B=B.reshape(T, R)
        R,T = B.shape
   

    C = np.zeros(shape=(M, T))
    
    if N==R:

        for i in range(M):
            for j in range(T):
                for k in range(0,N):
                    
                    C[i,j] += A[i,k]*(B[k,j])
        
        return C

a.

In [21]:
A=np.array([[5, -4, -2],[5, -5, 4],[2, 5, -4], [-5, 4, 3], [3, -4, -3]])
B=np.array([[5, -2, -3 ]])

print(multiplicacion(A, B))

[[ 39.]
 [ 23.]
 [ 12.]
 [-42.]
 [ 32.]]


b.

In [22]:
A=np.array([[0, -1, -1, 3],[5, -5, -2, 2],[1, 0, 4, 5]])
B=np.array([[0, -3], [-2, -1], [3, -3]])
print(multiplicacion(A, B))

None


c.

In [23]:
A=np.array([[2, -5, 5, 1],[5, 2, -7, -6],[-6, -1, 7, -4], [5, 4, 1, -5]])
B=np.array([[0, 4, -7, 1, -6], [-1, -6, -5, 1, 1], [2, -1, -6, 5, -5], [3, -6, 6, 3, 5]])
print(multiplicacion(A, B))

[[ 18.  27. -13.  25. -37.]
 [-34.  51. -39. -46. -23.]
 [  3.  -1. -19.  16. -20.]
 [-17.  25. -91.  -1. -56.]]


Utilizando dos matrices cuadradas, demuestre que la multiplicación no es conmutativa.

In [24]:
Matriz_1=np.array([[2, -5, 5, 1],[5, 2, -7, -6],[-6, -1, 7, -4], [5, 4, 1, -5]])
Matriz_2=np.array([[5, -4, -2, 8],[5, -5, 4, 2],[2, 5, -4, 1], [-5, 4, 3, 5]])

print("Al multiplicar la Matriz 1 por la Matriz 2 se obtiene: ")
print("\n")
print(multiplicacion(Matriz_1, Matriz_2))
print("\n")
print("Al multiplicar la Matriz 2 por la Matriz 1 se obtiene: ")
print("\n")
print(multiplicacion(Matriz_2, Matriz_1))
print("\n")
print("El resultado de multiplicar la matriz 1 por la matriz 2 no es igual al resultado de multiplicar\nla matriz 2 por la 1, con lo cual la multiplicación de matrices NO es conmutativa")


Al multiplicar la Matriz 1 por la Matriz 2 se obtiene: 


[[-10.  46. -41.  16.]
 [ 51. -89.   8.   7.]
 [ -1.  48. -32. -63.]
 [ 72. -55. -13.  24.]]


Al multiplicar la Matriz 2 por la Matriz 1 se obtiene: 


[[ 42.   1.  47.  -3.]
 [-29. -31.  90.   9.]
 [ 58.   8. -52. -17.]
 [ 17.  50. -27. -66.]]


El resultado de multiplicar la matriz 1 por la matriz 2 no es igual al resultado de multiplicar
la matriz 2 por la 1, con lo cual la multiplicación de matrices NO es conmutativa


EJERCICIO #2: (Reducción Gaussiana)

a. Forces on a Beam

In [25]:
def gaussian_elimination(A: np.array,b: np.array):
    '''
    Args:
        A (np.array): Matriz de coeficientes cuadrada (n x n).
        b (np.array): Vector de constantes de longitud n

    Returns:
        M (np.array): Matriz aumentada [A|b] reducida utilizando el algoritmo de eliminación Gaussiana
    '''
    n = np.shape(A)[0]
    M = np.zeros(shape=(n,n+1))
    M[:,0:n] = A
    M[:,n] = b
    for i in range (1,n):
        for j in range(0,i):
            C=(M[i,j]/M[j,j])
            M[i,:]=M[i,:]-C*M[j,:]
    

    return M

In [26]:
def back_substitution(A, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''

    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

In [27]:
A = np.array([[3,1,-1],\
              [1,-2,1],
              [4,-1,1]])
b = np.array([2,0,3])

In [28]:
M = gaussian_elimination(A,b)
Mnxn = M[:, :-1]
Mlast = M[:, -1]
F = back_substitution(Mnxn,Mlast)

In [29]:
print(f" Las fuerzas en orden F1, F2, F3 son {F}")

 Las fuerzas en orden F1, F2, F3 son [0.71428571 0.85714286 1.        ]


In [30]:
coeficientes = np.array([[3,1,-1],\
              [1,-2,1],
              [4,-1,1]])

# Definir el vector de términos constantes
constantes = np.array([2,0,3])

# Resolver el sistema de ecuaciones
solucion = np.linalg.solve(coeficientes, constantes)
print("comprobación:")
solucion

comprobación:


array([0.71428571, 0.85714286, 1.        ])

b. Current Flow

In [31]:
A = np.array([[1,1,1],\
              [0,-8,10],
              [4,-8,0]])
b = np.array([0,0,6])

In [32]:
M = gaussian_elimination(A,b)
Mnxn = M[:, :-1]
Mlast = M[:, -1]
I = back_substitution(Mnxn,Mlast)

In [33]:
print(f" Las corrientes en cada uno de los caminos en el orden I1, I2, I3 son {I}")

 Las corrientes en cada uno de los caminos en el orden I1, I2, I3 son [ 0.71052632 -0.39473684 -0.31578947]


EJERCICIO #3

In [43]:
import numpy as np

def valor_propio(k):
    z_sub_cero = np.array([3, 2, 1]) 
    w_sub_cero = z_sub_cero / np.linalg.norm(z_sub_cero)
    Matriz_A = np.array([[-2/3, 1/3, 0],[1/4, -2/4, 1/4],[0,1/5, -2/5]])

    for i in range(k):
        Z_k_1 = np.dot(Matriz_A, w_sub_cero)
        w_k_1 = Z_k_1 / np.linalg.norm(Z_k_1)

        w_sub_cero = w_k_1

    w_k_1_transpuesto = np.transpose(w_k_1)
    
    frecuencia=(np.dot(np.dot(w_sub_cero, Matriz_A), w_k_1_transpuesto))
    frecuencia=np.sqrt(-(np.dot(np.dot(w_sub_cero, Matriz_A), w_k_1_transpuesto)))

    return frecuencia, w_sub_cero


frecuencia, amplitud=valor_propio(20)
print("Se encontró un oscilación máxima (frecuencia máxima) del sistema de " +str(frecuencia)+ ",\nla cual está asociada a las siguientes amplitudes "+ str(amplitud))


Se encontró un oscilación máxima (frecuencia máxima) del sistema de nan,
la cual está asociada a las siguientes amplitudes [       nan 0.84089641        nan]


C:\Users\gaboe\AppData\Local\Temp\ipykernel_11216\3928099806.py:16: RuntimeWarning: invalid value encountered in sqrt
  w_sub_cero=np.sqrt(-w_sub_cero)


In [35]:
import numpy as np

def valor_propio(k):
    z_sub_cero = np.array([3, 2, 1])
    w_sub_cero = z_sub_cero / np.linalg.norm(z_sub_cero)

    Matriz_A = np.array([[-2/3, 1/3, 0],[1/4, -2/4, 1/4],[0,1/5, -2/5]]) #np.array([[-2, 1, 0],[1, -2, 1],[0,1 , -2]])
    Matriz_A_inversa= np.linalg.inv(Matriz_A)
    for i in range(k):
        Z_k_1 = np.dot(Matriz_A_inversa, w_sub_cero)
        w_k_1 = Z_k_1 / np.linalg.norm(Z_k_1)

        w_sub_cero = w_k_1

    w_k_1_transpuesto = np.transpose(w_k_1)
    
    

    return 1.0/(np.dot(np.dot(w_sub_cero, Matriz_A), w_k_1_transpuesto)), w_sub_cero


frecuencia, amplitud=valor_propio(20)
print("Se encontró un oscilación mínima (frecuencia mínima) del sistema de " +str(frecuencia)+ ",\nla cual está asociada a las siguientes amplitudes "+ str(amplitud))


Se encontró un oscilación mínima (frecuencia mínima) del sistema de -6.915475947401755,
la cual está asociada a las siguientes amplitudes [0.44914023 0.7034391  0.55085977]
